import type { Metadata } from "next";
// import { SessionProvider } from "next-auth/react";
import Variant from "@/context/Variant";
import "./globals.css";

export const metadata: Metadata = {
  title: "Fit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <SessionProvider> */}
        <Variant>{children}</Variant>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
